platform :ios, '8.0'
# use_frameworks!
inhibit_all_warnings!

pod 'JPSKeyboardLayoutGuide'
pod 'ReactiveCocoa', '~> 2.5'
pod 'CocoaLumberjack', '~> 2.2.0'
pod 'ErrorKit', '~> 0.3.1'
pod 'libextobjc', '~> 0.4'
pod 'ReactiveViewModel', '~> 0.3'
pod 'Objection', '1.6.1'
pod 'CrashlyticsLumberjack', '~> 2.0.5'
pod 'Crashlytics'
pod 'Masonry', '~> 0.6.1'
pod 'StaticDataTableViewController', '~> 2.0.3'
pod 'AFNetworking', '~> 2.5.0'
pod 'SVProgressHUD'
pod 'DTTableViewManager', '~>3.2.0'
pod 'DTCollectionViewManager', '~>3.2.0'
pod 'UINavigationBar+Addition'
# pod 'Fabric'